# Generated by Django 2.2 on 2020-12-11 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 23, 41, 48, 700554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 23, 41, 48, 762570, tzinfo=utc)),
        ),
    ]
