# Generated by Django 2.2 on 2021-02-11 21:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_richtextfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
